name: build-nginx

on:
  push:
    branches: 
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps: 
        - name: Checkout
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ secrets.DOCKER_HUB_USERNAME }}/dranoelweb:latest
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}